import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Sadim Stream",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-sans`}
      >
        <header className="w-full text-center flex items-center  h-[4rem] bg-black  border-b border-[#595c73]">
          <span className="font-xl text-white font-semibold px-2">Sadim stream </span>
        </header>
        {children}
      </body>
    </html>
  );
}
